name: 'OpenTofu AWS Deployment'

on:
  push:
    branches:
      - main

permissions:
  id-token: write # CRÍTICO: Permite a GitHub solicitar el token OIDC a AWS
  contents: read  # Permite a GitHub leer el código de tu repositorio

jobs:
  opentofu:
    name: 'Tofu Plan and Apply'
    runs-on: ubuntu-latest

    steps:
    # 1. Descarga el código de tu repositorio
    - name: Checkout Code
      uses: actions/checkout@v4

    # 2. Conecta GitHub con AWS usando OIDC de forma segura
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::040949441765:role/rol-github-actions-tofu # TU ARN REAL
        aws-region: us-east-1

    - name: Verify AWS Identity
      run: aws sts get-caller-identity

    # 3. Instala OpenTofu en el servidor de GitHub
    - name: Setup OpenTofu
      uses: opentofu/setup-opentofu@v1
      with:
        tofu_version: 1.8.8

    # 4. Inicializa OpenTofu leyendo el backend S3 en AWS
    - name: OpenTofu Init
      run: tofu init

    # 5. Simulación de los cambios a realizar
    - name: OpenTofu Plan
      run: tofu plan

    # 6. Aplica los cambios automáticamente en AWS
    - name: OpenTofu Apply
      run: tofu apply -auto-approve